export const ON_USER_JOIN = 'ON_USER_JOIN'
export const ON_USER_LEFT = 'ON_USER_LEFT'
export const ON_USER_MOVE = 'ON_USER_MOVE'
export const ON_USER_STOP = 'ON_USER_STOP'
export const ON_EGG_PICK = 'ON_EGG_PICK'
